services:
  traefik:
    container_name: traefik
    image: traefik:v2.2
    command:
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  drupal:
    image: drupal_php_extensions
    container_name: drupal
    depends_on:
      - db
    links:
      - db
    labels:
      - "traefik.http.routers.drupal.entrypoints=websecure"
      - "traefik.http.routers.drupal.rule=Host(${SITES})"
      - "traefik.http.routers.drupal.tls=true"
    volumes:
      - ${FILES_PATH}drupal_site/drupal:/opt/drupal
      - ./drupal_ini/ob.ini:/usr/local/etc/php/conf.d/ob.ini
    restart: always

  db:
    image: mariadb:10.11
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PW}
      # the below must match those that are stated in your settings.php file
      MYSQL_DATABASE: ${DRUPAL_DB}
      MYSQL_USER: ${DRUPAL_USER}
      MYSQL_PASSWORD: ${DRUPAL_PW}
    volumes:
      - ${FILES_PATH}drupal_db/:/var/lib/mysql
      - ./db_cnf/transaction_isolation.cnf:/etc/mysql/conf.d/transaction_isolation.cnf

  metabase:
    image: metabase/metabase:v0.50.27
    container_name: metabase
    hostname: metabase
    labels:
      - "traefik.http.routers.metabase.entrypoints=websecure"
      - "traefik.http.routers.metabase.rule=Host(${REPORTS})"
      - "traefik.http.routers.metabase.tls=true"
      - "traefik.http.services.metabase.loadbalancer.server.port=3000"
    links:
      - postgres
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: ${MB_DB_DBNAME}
      MB_DB_USER: ${MB_DB_USER}
      MB_DB_PASS: ${MB_DB_PASS}
      MB_DB_HOST: ${MB_DB_HOST}

  postgres:
    image: postgres:17
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: ${MB_DB_USER}
      POSTGRES_DB: ${MB_DB_DBNAME}
      POSTGRES_PASSWORD: ${MB_DB_PASS}
    volumes:
      - ${FILES_PATH}pgdata:/var/lib/postgresql/data

  # phpmyadmin:
  #   image: phpmyadmin:5.2.1
  #   depends_on: 
  #     - db  
  #   restart: always
  #   environment:
  #     PMA_HOST: db
  #     PMA_USER: ${DRUPAL_USER}
  #     PMA_PASSWORD: ${DRUPAL_PW}
  #     UPLOAD_LIMIT: 300M
  #   ports:
  #     - 8080:80

  # maildev:
  #   image: maildev/maildev
  #   container_name: maildev
  #   restart: always
  #   ports:
  #     - 1080:1080
  #     - 1025:1025
